name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'img/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'img/**'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y libarchive-tools binutils-aarch64-linux-gnu binutils-arm-linux-gnueabihf
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Validation
      uses: gradle/wrapper-validation-action@v2
      
    - name: Java setup
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Restore cache
      uses: actions/cache@v4
      with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

          restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Build
      run: ./gradlew assembleDebug
    - name: Build companion package
      run: ./build_termux_package
    - name: Copy loader to target directory
      run:  cp ./shell-loader/build/outputs/apk/debug/shell-loader-debug.apk ./app/build/outputs/apk/debug/shell-loader-nightly.apk
    
    - name: Store app-armeabi-v7a-debug
      uses: actions/upload-artifact@v4
      with:
        name: termux-x11-armeabi-v7a-debug
        path: ./app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
        
    - name: Store unstripped libraries with debug symbols
      uses: actions/upload-artifact@v4
      with:
        name: termux-x11-unstripped-libraries-for-ndk-stack
        path: ./app/build/intermediates/cxx/Debug/*

    # - name: Update Nightly Release
    #   uses: andelf/nightly-release@main
    #   if: github.repository == 'termux/termux-x11' && github.ref == 'refs/heads/master'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: nightly
    #     name: 'Nightly Release $$'
    #     draft: false
    #     prerelease: false
    #     body: |
    #       This is a nightly release of the termux-x11 app.
    #       Based on ${{ github.sha }}
    #     files: |
    #       ./app/build/outputs/apk/debug/app-*-debug.apk
    #       ./app/build/outputs/apk/debug/shell-loader-nightly.apk
    #       ./app/build/outputs/apk/debug/termux-x11-*-all.deb
    #       ./app/build/outputs/apk/debug/termux-x11-*-any.pkg.tar.xz
